{% set name = "eoftoolkit" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 7e374294e8b9a30a770522bbae635a4251748cbe1274acc62d4bc0c0f7a9e958

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.8
    - poetry-core >=1.0.0
    - pip
  run:
    - python >=3.8
    - numpy >=1.20.0
    - scipy >=1.7.0
    - pandas >=1.3.0
    - netcdf4 >=1.5.0

test:
  imports:
    - eoftoolkit
    - eoftoolkit.core
    - eoftoolkit.analysis
    - eoftoolkit.visualization
    - eoftoolkit.io
  commands:
    - python -c "from eoftoolkit.core.processor import EOFProcessor; print('Import test passed')"

about:
  home: https://github.com/Mkord99/EOFtoolkit
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A comprehensive Python toolkit for Empirical Orthogonal Function (EOF) analysis
  description: |
    EOFtoolkit is a comprehensive Python library for Empirical Orthogonal Function (EOF) 
    analysis, designed for climate scientists, meteorologists, oceanographers, and researchers 
    working with spatiotemporal data analysis.
  doc_url: https://github.com/Mkord99/EOFtoolkit
  dev_url: https://github.com/Mkord99/EOFtoolkit

extra:
  recipe-maintainers:
    - mohammadkord99
